### ISSUE TITLE
Fails to persist data on GCS Blob unknown to registry.

### ISSUE THREAD

**Issue by kailashyogeshwar85** [triggermesh/knative-local-registry#14]
I have made changes to registry-config.yaml to use GCS for persisting data. Images are build & pushed using 
``` bash
minikube ssh -p knative
docker build -t knative.registry.svc.cluster.local/hellotest:latest 
docker push knative.registry.svc.cluster.local/hellotest:latest
```
Registry ConfigMap
``` yaml
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
apiVersion: v1
data:
  config.yml: |-
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
      formatter: json
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
      gcs:
        bucket: knativetest
        credentials:
          type: service_account
          project_id: swift-cursor-272514
          private_key_id: 
          private_key: 
          client_email: 
          client_id: 
          auth_uri: https://accounts.google.com/o/oauth2/auth
          token_uri: https://oauth2.googleapis.com/token
          auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
          client_x509_cert_url: 
    http:
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    validation:
       disabled: true

```

``` 
192.168.122.33 - - [30/Mar/2020:12:01:06 +0000] "HEAD /v2/registrytest/hellotest/blobs/sha256:352dc97a8b9c07eedacb01ece1f141db065acc2d56a1321d21310b02b532b7b1 HTTP/1.1" 200 0 "" "docker/19.03.6 go/go1.12.16 git-commit/369ce74a3c kernel/4.19.94 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.6 \\(linux\\))"
192.168.122.33 - - [30/Mar/2020:12:01:06 +0000] "HEAD /v2/registrytest/hellotest/blobs/sha256:5a63fdc09f839e1d33c34c7adf03b13ee26340cb686ea1983781f5e1335445b1 HTTP/1.1" 404 157 "" "docker/19.03.6 go/go1.12.16 git-commit/369ce74a3c kernel/4.19.94 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.6 \\(linux\\))"
time="2020-03-30T12:01:06.519971313Z" level=error msg="response completed with error" err.code="blob unknown" err.detail=sha256:5a63fdc09f839e1d33c34c7adf03b13ee26340cb686ea1983781f5e1335445b1 err.message="blob unknown to registry" go.version=go1.11.2 http.request.host=knative.registry.svc.cluster.local http.request.id=2c97743f-fa26-4faf-bd50-51fb6f0913ed http.request.method=HEAD http.request.remoteaddr="192.168.122.33:34202" http.request.uri="/v2/registrytest/hellotest/blobs/sha256:5a63fdc09f839e1d33c34c7adf03b13ee26340cb686ea1983781f5e1335445b1" http.request.useragent="docker/19.03.6 go/go1.12.16 git-commit/369ce74a3c kernel/4.19.94 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.6 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration="763.404µs" http.response.status=404 http.response.written=157 vars.digest="sha256:5a63fdc09f839e1d33c34c7adf03b13ee26340cb686ea1983781f5e1335445b1" vars.name="registrytest/hellotest" 
time="2020-03-30T12:01:06.525294383Z" level=info msg="response completed" go.version=go1.11.2 http.request.host=knative.registry.svc.cluster.local http.request.id=1d629fbc-4500-4f3a-a9c1-7cef40c730ed http.request.method=POST http.request.remoteaddr="192.168.122.33:34204" http.request.uri="/v2/registrytest/hellotest/blobs/uploads/" http.request.useragent="docker/19.03.6 go/go1.12.16 git-commit/369ce74a3c kernel/4.19.94 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.6 \(linux\))" http.response.duration=4.451374ms http.response.status=202 http.response.written=0 
192.168.122.33 - - [30/Mar/2020:12:01:06 +0000] "POST /v2/registrytest/hellotest/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/19.03.6 go/go1.12.16 git-commit/369ce74a3c kernel/4.19.94 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.6 \\(linux\\))"
```
